version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: ./build.ps1
test_script:
- ps: ./test.ps1
artifacts:
- path: src/microscopic/bin/Release/netstandard2.0
  name: netstandard20
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md